# Generated by Django 5.2.5 on 2025-11-17 16:56

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scheduler_course',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'scheduler_semester',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('INSTRUCTOR', 'Instructor')], default='INSTRUCTOR', max_length=20)),
                ('instructor_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='scheduler.course')),
            ],
            options={
                'db_table': 'scheduler_curriculum',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'scheduler_department',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_department_name'), models.UniqueConstraint(fields=('code',), name='unique_department_code')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduler.department'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_roles', models.CharField(blank=True, help_text='Comma-separated roles (ADMIN, INSTRUCTOR)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='scheduler.department')),
            ],
            options={
                'db_table': 'scheduler_announcement',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduler_instructor',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('room_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory')], default='LECTURE', max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='scheduler.department')),
            ],
            options={
                'db_table': 'scheduler_room',
            },
        ),
        migrations.CreateModel(
            name='SchoolYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='Format: YY-# (e.g. 25-1, 25-2)', max_length=20)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_year_levels', to='scheduler.curriculum')),
            ],
            options={
                'db_table': 'scheduler_schoolyearlevel',
                'ordering': ['school_year'],
                'unique_together': {('curriculum', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
                ('year_level', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scheduler.course')),
            ],
            options={
                'db_table': 'scheduler_section',
                'unique_together': {('course', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('units', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('lecture_units', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('lab_units', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('tf_units', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('load_units', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('prerequisite', models.CharField(blank=True, max_length=100, null=True)),
                ('required_hours_per_week', models.PositiveIntegerField(default=3)),
                ('meeting_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory')], default='LECTURE', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('day', models.CharField(blank=True, max_length=100, null=True)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scheduler.curriculum')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_instructor', to='scheduler.instructor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='scheduler.room')),
                ('school_year_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='scheduler.schoolyearlevel')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_subjects', to='scheduler.section')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.semester')),
            ],
            options={
                'db_table': 'scheduler_subject',
            },
        ),
        migrations.AddField(
            model_name='instructor',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='qualified_instructors', to='scheduler.subject'),
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_levels', to='scheduler.curriculum')),
            ],
            options={
                'db_table': 'scheduler_yearlevel',
                'unique_together': {('curriculum', 'year')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='year_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.yearlevel'),
        ),
        migrations.AddField(
            model_name='semester',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='scheduler.yearlevel'),
        ),
        migrations.CreateModel(
            name='CurriculumRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Revision name, e.g. Rev. 1, Rev. 2025', max_length=100)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scheduler.curriculum')),
            ],
            options={
                'db_table': 'scheduler_curriculum_revision',
                'ordering': ['-effective_date', 'name'],
                'unique_together': {('curriculum', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduler.instructor')),
            ],
            options={
                'db_table': 'scheduler_instructor_availability',
                'indexes': [models.Index(fields=['instructor', 'day', 'start_time', 'end_time'], name='scheduler_i_instruc_cc489e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduler.room')),
            ],
            options={
                'db_table': 'scheduler_room_availability',
                'indexes': [models.Index(fields=['room', 'day', 'start_time', 'end_time'], name='scheduler_r_room_id_2fedc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('time_start', models.TimeField(default=datetime.time(8, 0))),
                ('time_end', models.TimeField(default=datetime.time(9, 0))),
                ('meeting_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('LABORATORY', 'Laboratory')], default='LECTURE', max_length=20)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.instructor')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.subject')),
            ],
            options={
                'db_table': 'scheduler_schedule',
                'ordering': ['day', 'time_start'],
                'indexes': [models.Index(fields=['day', 'time_start', 'time_end'], name='scheduler_s_day_71b53f_idx'), models.Index(fields=['room', 'day', 'time_start', 'time_end'], name='scheduler_s_room_id_f1f0c7_idx'), models.Index(fields=['instructor', 'day', 'time_start', 'time_end'], name='scheduler_s_instruc_246088_idx'), models.Index(fields=['section', 'day', 'time_start', 'time_end'], name='scheduler_s_section_0ed583_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year_level', 'semester_number')},
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='scheduler.curriculum')),
                ('school_year_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='scheduler.schoolyearlevel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='scheduler.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
                ('year_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='scheduler.yearlevel')),
            ],
            options={
                'db_table': 'scheduler_curriculum_subject',
                'ordering': ['order'],
                'unique_together': {('curriculum', 'year_level', 'semester', 'subject')},
            },
        ),
    ]
