# Generated by Django 5.2.5 on 2025-11-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock this semester to prevent adding new subjects'),
        ),
        migrations.AddField(
            model_name='semester',
            name='locked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='school_year',
            field=models.CharField(blank=True, help_text='Format: 25-1 (Year-Term)', max_length=20, null=True),
        ),
    ]
