# Generated by Django 5.2.5 on 2025-11-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_semester_is_locked_semester_locked_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='locked_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='school_year',
        ),
    ]
