# Generated by Django 5.2.5 on 2025-11-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_semester_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_name', 'semester')},
        ),
    ]
